import { Poppins } from 'next/font/google'
import { ReactNode } from 'react'
import '../styles/globals.css'
import Provider from './Provider'
import { GlobalContextProvider } from '@/context/global'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="bg-gray-1 dark-theme">
        <Provider>
          <GlobalContextProvider>{children}</GlobalContextProvider>
        </Provider>
      </body>
    </html>
  )
}
